Made SNMP privacy protocol selectable
wernerfred/check_synology pull request #41
Opened 2022-08-15 11:21 UTC by dommi22m

This is my version to make the privacy protocol selectable. AES128 is used as default.

2022-08-15 12:27 UTC, wernerfred requested changes
LGTM 👍🏻 

Please add the new option `[-s [AES128|DES]]` to the usage in the `README.md` accordingly.

Why specifically did you choose `-s`? Maybe we should change this to `-e`(encryption?) to save `-s` for future usecases that are more related to the letter `s`? What's your opinion on that?

2022-08-16 08:13 UTC, dommi22m commented
> Please add the new option [-s [AES128|DES]] to the usage in the README.md accordingly.
Done!

> Why specifically did you choose -s? Maybe we should change this to -e(encryption?) to save -s for future usecases that are more related to the letter s? What's your opinion on that?
Yes you are right! I was thinking in the direction of "secret". But that would not be logical and also wrong in terms of content.

2022-08-16 10:24 UTC, wernerfred requested changes
Small whitespace fix, rest LGTM 👍🏻

2022-08-16 10:24 UTC, wernerfred commented on README.md
> +usage: check_synology [-h] [-w W] [-c C] [-p PORT] [-e PROTOCOL ] hostname username authkey privkey {load,memory,disk,storage,update,status}
```suggestion
usage: check_synology [-h] [-w W] [-c C] [-p PORT] [-e PROTOCOL] hostname username authkey privkey {load,memory,disk,storage,update,status}
```

2022-08-16 10:25 UTC, wernerfred commented
@all-contributors add @dommi22m for code

2024-01-08 14:00 UTC, wernerfred approved these changes

2024-01-08 14:01 UTC, merged